mirror-to-github:
  stage: deploy
  image: bitnami/git:latest
  only:
    - main
  script:
    - git push --force https://buildeployship:$GITHUB_TOKEN@github.com/buildeployship/$CI_PROJECT_NAME.git HEAD:main
